### ISSUE TITLE
能支持收费歌曲吗？

### ISSUE THREAD

**Issue by heroboy** [Chion82/163_music_cracker#2]
我发现收费歌曲的mp3地址其实也是拿的到的。

**Comment by Chion82** [comment]
提议很好。网页端的API设计很不严谨，mp3Url甚至是没有屏蔽的。收费歌曲只是改一个歌曲的fee参数即可。刚才我已经改好了，测试了几个收费歌曲都没有问题

**Comment by Chion82** [comment]
@heroboy firefox插件请定向core.js到https://cdn.rawgit.com/Chion82/163_music_cracker/373fe0398dd8c3380db8bb06d06d38c6f3bee082/core.js

**Comment by heroboy** [comment]
可以使用，非常感谢。
